[package]
name = "nearfm-contract"
version = "0.1.0"
edition = "2021"

[package.metadata.near.build]
wasm-opt-args = ["--enable-bulk-memory"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
abi = ["borsh/unstable__schema"]

[dependencies]
near-sdk = { version = "= 5.17.2", features = ["legacy"] }
schemars = "0.8"
borsh = { version = "1.5", features = ["derive"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
