import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rules — near.fm",
  description: "Community guidelines and content policy for near.fm",
};

export default function RulesPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-white mb-2">Community Rules</h1>
      <p className="text-slate-400 text-sm mb-10">
        By using near.fm you agree to follow these guidelines. Violations may result in content removal or account suspension.
      </p>

      <div className="space-y-10">
        {/* Content Policy */}
        <section>
          <h2 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-purple-500/15 text-purple-400 flex items-center justify-center text-sm font-bold">1</span>
            Content Policy
          </h2>
          <div className="glass-card rounded-xl p-5 space-y-3 text-sm text-slate-300 leading-relaxed">
            <p>
              <strong className="text-white">near.fm is a platform for AI-generated music about the NEAR ecosystem, crypto, and AI.</strong> We
              expect uploaded songs to be related to these topics.
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-slate-400">
              <li>Only upload music that was <strong className="text-slate-200">generated by AI</strong> (Suno, Udio, or similar tools).</li>
              <li>Only upload cover images that you created or generated — do not use copyrighted artwork.</li>
              <li>Do not upload music or images to which you do not hold the rights.</li>
              <li>Songs should have meaningful lyrics and reasonable duration. Tracks that are too short, have no
                lyrics, or are otherwise low-quality may be hidden by moderators.</li>
              <li>Repeated uploads of low-quality content may result in your account being suspended.</li>
            </ul>
          </div>
        </section>

        {/* Community Guidelines */}
        <section>
          <h2 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-cyan-500/15 text-cyan-400 flex items-center justify-center text-sm font-bold">2</span>
            Community Guidelines
          </h2>
          <div className="glass-card rounded-xl p-5 space-y-3 text-sm text-slate-300 leading-relaxed">
            <ul className="list-disc list-inside space-y-1.5 text-slate-400">
              <li>Be respectful in comments and interactions. No hate speech, harassment, or personal attacks.</li>
              <li>No content that promotes violence, discrimination, or illegal activity.</li>
              <li>No spam, scams, or misleading content (including fake bounty requests).</li>
              <li>Do not impersonate other users or projects.</li>
              <li>Song requests and bounties must be made in good faith.</li>
            </ul>
          </div>
        </section>

        {/* Reputation & Tipping */}
        <section>
          <h2 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-amber-500/15 text-amber-400 flex items-center justify-center text-sm font-bold">3</span>
            Reputation & Tipping
          </h2>
          <div className="glass-card rounded-xl p-5 space-y-3 text-sm text-slate-300 leading-relaxed">
            <p>
              Every user has a <strong className="text-white">reputation score</strong> that reflects their contribution to the platform.
              Reputation is earned by uploading quality songs, receiving tips, sending tips to other creators, and gaining followers.
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-slate-400">
              <li>Tips sent and received increase your reputation — this is verified on-chain and cannot be faked.</li>
              <li>Users with higher reputation have more influence on song rankings through their votes.</li>
              <li>Votes from low-reputation accounts carry reduced weight to prevent manipulation.</li>
              <li>All tips are recorded on the NEAR blockchain and can be independently verified.</li>
            </ul>
          </div>
        </section>

        {/* Moderation */}
        <section>
          <h2 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-rose-500/15 text-rose-400 flex items-center justify-center text-sm font-bold">4</span>
            Moderation
          </h2>
          <div className="glass-card rounded-xl p-5 space-y-3 text-sm text-slate-300 leading-relaxed">
            <p>Moderators may take the following actions at their discretion:</p>
            <ul className="list-disc list-inside space-y-1.5 text-slate-400">
              <li>Hide songs that violate content policy or are low-quality.</li>
              <li>Hide or remove comments that violate community guidelines.</li>
              <li>Mute users who repeatedly post inappropriate comments.</li>
              <li>Ban accounts that engage in persistent rule violations.</li>
            </ul>
            <p className="text-slate-500 text-xs mt-2">
              If you believe a moderation action was taken in error, please reach out via the community channels.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
